import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Error from 'next/error';
import TakeShape from '../takeshape.client';
import Navigatie from '../components/navigatie';
import { getWishes } from '../lib/api'



export async function getStaticProps() {
  try {
    const res = await TakeShape.graphql({query: ''});
    return {
      props: {
        graphQlAPIWorks: res.ok
      }
    };
  } catch (error) {
    return {
      props: {
        error: error.message
      }
    };
  }
}
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navigatie />
      
      <main className={styles["main"]}>
	{/* <!-- De zoekbalk voor het zoeken naar wensen --> */}
	<article className={styles["searchbar"]}>
		<form method="get" action="/">
			<label hidden for="search">Zoeken</label>
			<input  id="search-wishes" type="search" name="q" />
			<button>
				<figure>
					<svg
						xmlns="http://www.w3.org/2000/svg"
						className={styles["icon icon-tabler icon-tabler-search"]}
						width="24"
						height="24"
						viewBox="0 0 24 24"
						stroke-width="2"
						stroke="currentColor"
						fill="none"
						stroke-linecap="round"
						stroke-linejoin="round"
					>
						<path stroke="none" d="M0 0h24v24H0z" fill="none" />
						<path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" />
						<path d="M21 21l-6 -6" />
					</svg>
					<figcaption>zoeken</figcaption>
				</figure>
			</button>
		</form>
	</article>

	<section className={styles["section"]}>
		{/* <!-- Alle wensen uit de Hygraph API  --> */}
		{/* {res.forEach()}
			<article className={styles["card_article"]}>
				<div className={styles["card_image"]}>
					<img
						src={wish.image.url}
						alt="foto van {wish.heading}"
						width={wish.image.width}
						height={wish.image.height}
						className={styles["card_img"]}
					/>
					<div className={styles["card_image_body"]}>
						<h3>Beschrijving:</h3>
						<p className={styles["card_description"]}>
							{wish.description}
						</p>
					</div>
				</div>

				<div className={styles["card_data"]}>
					<h2>{wish.heading}</h2>
					<span className={styles["card_date"]}>Geplaats op: {wish.date}</span>
					<div className={styles["card_label"]}>
						<svg xmlns="http://www.w3.org/2000/svg" height="13px" viewBox="0 0 448 512"
							><style>
								svg {
									fill: #c2c2c2;
								}
							</style><path
								d="M0 80V229.5c0 17 6.7 33.3 18.7 45.3l176 176c25 25 65.5 25 90.5 0L418.7 317.3c25-25 25-65.5 0-90.5l-176-176c-12-12-28.3-18.7-45.3-18.7H48C21.5 32 0 53.5 0 80zm112 32a32 32 0 1 1 0 64 32 32 0 1 1 0-64z"
							/></svg
						>
						<span>{wish.label}</span>
					</div>
					<h3>Supporters: <span>4</span></h3>
					<a href="/wens/{wish.id}" className={styles["button"]}>Lees meer</a>
				</div>
			</article> */}

	</section>
</main>
    </>
  )
}
